CREATE TABLE HOUSES (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(255) UNIQUE NOT NULL,
  WORDS VARCHAR(255) NOT NULL
);

CREATE TABLE CHARACTERS (
  ID SERIAL PRIMARY KEY,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  HOUSE LONG NOT NULL,
  FOREIGN KEY (HOUSE) REFERENCES HOUSES (ID)
);
